// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:06085579-3881-4030-bc0f-8e936f8f0f52",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_h0xBaJvIH",
    "aws_user_pools_web_client_id": "2chm6buifafdifkanq78e3g6gs",
    "aws_appsync_graphqlEndpoint": "https://ofu6xy23tnfv3cfer75ytqrdmm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
